name: CI / CD Test
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: 'Create env file'
        run: |
          echo VITE_API_URL=http://64.226.100.37/api > .env
          
      - name: Build Docker Image
        run: |
          docker build -t tester/frontend .
          docker save tester/frontend | gzip > frontend.tar.gz
          
      - name: Copy Docker Image Archive via SCP
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "frontend.tar.gz"
          target: "/opt"

      
      - name: Deploy Docker Image on Remote Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker load -i /opt/frontend.tar.gz
            rm /opt/frontend.tar.gz
            docker compose up -d --build
